#!/usr/bin/env bash
#
# Guards for deploy.sh, upload_assets.sh and phase0/upload_disc.sh.
#
# Nothing here touches Cloudflare. Every case ends in a refusal or in a dry run, which only
# prints the command it would have run -- that is the point: these are the paths that decide
# whether an unattended run can publish something, so they have to fail closed, and the only
# way to know that they do is to try to make them publish.
#
# The fixture is its own git repository: the real checkout may be dirty while this runs, and
# the "uncommitted changes" guard has to be exercised on a tree whose state this test owns.
#
# Run with:  bash scripts/tests/test_deploy_guard.sh
set -euo pipefail

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

failures=0

fail() {
  echo "FAIL: $*" >&2
  failures=$((failures + 1))
}

# expect_refusal <label> <expected status> <expected text> <command...>
expect_refusal() {
  local label="$1" expected_status="$2" expected_text="$3"
  shift 3
  local status out
  set +e
  out=$("$@" 2>&1)
  status=$?
  set -e
  if [ "$status" -eq 0 ]; then
    fail "$label: expected a refusal, but it exited 0"
    awk '{print "    " $0}' <<<"$out" >&2
    return
  fi
  if [ "$status" -ne "$expected_status" ]; then
    fail "$label: exited $status, expected $expected_status"
    awk '{print "    " $0}' <<<"$out" >&2
    return
  fi
  grep -q "$expected_text" <<<"$out" ||
    fail "$label: the message does not mention '$expected_text'"
  echo "ok: $label"
}

# --- fixture repository ---------------------------------------------------------------------
# web/dist is git-ignored here, as it is in the real repository, so that a missing _headers
# can be tested without the tree also being dirty: those are two different refusals.
repo="$tmp/repo"
mkdir -p "$repo/web/dist"
printf 'web/dist/\n' >"$repo/.gitignore"
printf '/*\n  Cross-Origin-Opener-Policy: same-origin\n' >"$repo/web/dist/_headers"
printf '<!doctype html><title>fixture</title>\n' >"$repo/web/dist/index.html"
git -C "$repo" init -q -b main
git -C "$repo" -c user.name=guard -c user.email=guard@local add -A
git -C "$repo" -c user.name=guard -c user.email=guard@local commit -q -m "fixture tree"

# --- fixture assets, generated by the real generator ----------------------------------------
assets="$tmp/assets-extracted"
mkdir -p "$assets/files/audio/us"
printf 'GALE01%.0s' {1..512} >"$assets/files/opening.bnr"
head -c 2048 /dev/urandom >"$assets/files/audio/us/12.hps"
printf 'stage' >"$assets/files/GrSh.dat"
printf 'unknown' >"$assets/files/unknown.bin"
manifest="$tmp/assets/manifest.json"
python3 "$root/scripts/make_manifest.py" --assets "$assets" --out "$manifest" >/dev/null

deploy=(bash "$root/scripts/deploy.sh")
upload=(bash "$root/scripts/upload_assets.sh")

# 1. No credentials: the one thing that must never happen is a deploy without them.
expect_refusal "deploy without credentials" 2 "CLOUDFLARE_API_TOKEN" \
  env -u CLOUDFLARE_API_TOKEN -u CLOUDFLARE_ACCOUNT_ID -u CF_PAGES_PROJECT \
  "${deploy[@]}" --repo-dir "$repo" --dist-dir "$repo/web/dist"

# 2. Dirty tree: the deployed shell has to correspond to a commit.
printf 'wip\n' >"$repo/wip.txt"
expect_refusal "deploy with a dirty tree" 3 "uncommitted changes" \
  env CLOUDFLARE_API_TOKEN=dummy CLOUDFLARE_ACCOUNT_ID=dummy CF_PAGES_PROJECT=melee-web \
  "${deploy[@]}" --repo-dir "$repo" --dist-dir "$repo/web/dist"
rm -f "$repo/wip.txt"

# 3. dist without _headers: the shell would deploy without COOP/COEP.
mv "$repo/web/dist/_headers" "$tmp/_headers"
expect_refusal "deploy without dist/_headers" 4 "run scripts/build_web.sh" \
  env CLOUDFLARE_API_TOKEN=dummy CLOUDFLARE_ACCOUNT_ID=dummy CF_PAGES_PROJECT=melee-web \
  "${deploy[@]}" --repo-dir "$repo" --dist-dir "$repo/web/dist"
mv "$tmp/_headers" "$repo/web/dist/_headers"

# 4. The happy path, as far as it can be exercised here: a dry run that names the command,
#    the project and the branch, and that does not echo the token.
set +e
dry=$(env CLOUDFLARE_API_TOKEN=dummy-token-value CLOUDFLARE_ACCOUNT_ID=dummy CF_PAGES_PROJECT=melee-web \
  "${deploy[@]}" --dry-run --repo-dir "$repo" --dist-dir "$repo/web/dist" 2>&1)
dry_status=$?
set -e
if [ "$dry_status" -ne 0 ]; then
  fail "deploy --dry-run exited $dry_status"
  awk '{print "    " $0}' <<<"$dry" >&2
else
  grep -q "pages deploy" <<<"$dry" || fail "deploy --dry-run does not print the wrangler command"
  grep -q "melee-web" <<<"$dry" || fail "deploy --dry-run does not print the project name"
  grep -q "dummy-token-value" <<<"$dry" && fail "deploy --dry-run echoed the API token"
  echo "ok: deploy --dry-run prints the command without the token"
fi

# 4b. The dist does not have to be inside the repository: CI deploys $RUNNER_TEMP/spike-dist.
#     docs/PHASE0_DEPLOY_PLAN.md section 3 asked whether anything else blocks that, and the
#     answer is that the only checks reading the dist are `_headers` and `index.html` -- neither
#     is about where the dist sits.
outside="$tmp/outside-dist"
mkdir -p "$outside"
cp "$repo/web/dist/_headers" "$repo/web/dist/index.html" "$outside/"
set +e
dry_outside=$(env CLOUDFLARE_API_TOKEN=dummy CLOUDFLARE_ACCOUNT_ID=dummy CF_PAGES_PROJECT=melee-web \
  "${deploy[@]}" --dry-run --repo-dir "$repo" --dist-dir "$outside" 2>&1)
outside_status=$?
set -e
if [ "$outside_status" -ne 0 ]; then
  fail "deploy --dry-run refused a dist outside the repository (exit $outside_status)"
  awk '{print "    " $0}' <<<"$dry_outside" >&2
else
  grep -q "$outside" <<<"$dry_outside" || fail "deploy --dry-run does not name the dist it was given"
  echo "ok: deploy --dry-run accepts a dist outside the repository"
fi

# 4c. A linked worktree is a checkout. Its `.git` is a *file*, and the guard used to answer
#     "is this a checkout?" with the filesystem, so it refused a clean worktree as
#     "not a git checkout" while accepting a clone. This repository is worked in worktrees.
worktree="$tmp/worktree"
git -C "$repo" worktree add -q "$worktree" -b guard-worktree
[ -f "$worktree/.git" ] || fail "the fixture worktree does not have a .git file"
mkdir -p "$worktree/web/dist"
cp "$repo/web/dist/_headers" "$repo/web/dist/index.html" "$worktree/web/dist/"
set +e
dry_worktree=$(env CLOUDFLARE_API_TOKEN=dummy CLOUDFLARE_ACCOUNT_ID=dummy CF_PAGES_PROJECT=melee-web \
  "${deploy[@]}" --dry-run --repo-dir "$worktree" --dist-dir "$worktree/web/dist" 2>&1)
worktree_status=$?
set -e
if [ "$worktree_status" -ne 0 ]; then
  fail "deploy --dry-run refused a linked worktree (exit $worktree_status)"
  awk '{print "    " $0}' <<<"$dry_worktree" >&2
else
  echo "ok: deploy --dry-run accepts a linked worktree"
fi

# 4d. A directory that is not a checkout at all is still refused: the guard keeps failing closed.
mkdir -p "$tmp/not-a-checkout"
expect_refusal "deploy from a directory that is not a checkout" 3 "is not a git checkout" \
  env CLOUDFLARE_API_TOKEN=dummy CLOUDFLARE_ACCOUNT_ID=dummy CF_PAGES_PROJECT=melee-web \
  "${deploy[@]}" --repo-dir "$tmp/not-a-checkout" --dist-dir "$repo/web/dist"

# 5. Asset upload without credentials.
expect_refusal "upload --apply without credentials" 2 "CLOUDFLARE_API_TOKEN" \
  env -u CLOUDFLARE_API_TOKEN -u CLOUDFLARE_ACCOUNT_ID \
  "${upload[@]}" --apply --manifest "$manifest" --store "$tmp/assets/store"

# 6. Asset upload refuses a store that does not hold every object the manifest names.
manifest_nostore="$tmp/assets/manifest-nostore.json"
python3 "$root/scripts/make_manifest.py" --assets "$assets" --out "$manifest_nostore" --no-store >/dev/null
expect_refusal "upload with an incomplete store" 3 "does not hold every object" \
  "${upload[@]}" --manifest "$manifest_nostore" --store "$tmp/absent-store"

# 7. The asset dry run needs no credentials, and it is what the operator reads before the
#    real upload.
set +e
plan=$(env -u CLOUDFLARE_API_TOKEN -u CLOUDFLARE_ACCOUNT_ID \
  "${upload[@]}" --manifest "$manifest" --store "$tmp/assets/store" 2>&1)
plan_status=$?
set -e
if [ "$plan_status" -ne 0 ]; then
  fail "upload dry run exited $plan_status"
  awk '{print "    " $0}' <<<"$plan" >&2
else
  grep -q "dry run: nothing is uploaded" <<<"$plan" || fail "upload dry run does not say it uploaded nothing"
  grep -q "4 distinct blob(s)" <<<"$plan" || fail "upload dry run does not count the four distinct blobs"
  echo "ok: upload dry run lists the plan without credentials"
fi

# 8. Disc upload requires S3 credentials, including in the default dry run.
disc_upload="$root/scripts/phase0/upload_disc.sh"
for mode in --dry-run --apply; do
  expect_refusal "disc $mode without credentials" 2 "R2_ACCESS_KEY_ID" \
    env -u CLOUDFLARE_ACCOUNT_ID -u R2_ACCESS_KEY_ID -u R2_SECRET_ACCESS_KEY \
    bash "$disc_upload" "$mode" --iso "$tmp/absent.iso"
done

# 9. Wrong size and correct size with wrong SHA-1 both fail before any PUT.
# truncate creates a sparse zero fixture outside the repo, not a copy of game data.
printf 'invalid disc' >"$tmp/wrong.iso"
for mode in --dry-run --apply; do
  expect_refusal "disc $mode wrong size" 3 "ISO size must be" \
    env CLOUDFLARE_ACCOUNT_ID=dummy R2_ACCESS_KEY_ID=dummy R2_SECRET_ACCESS_KEY=dummy \
    bash "$disc_upload" "$mode" --iso "$tmp/wrong.iso" --out "$tmp/chunks.json"
done
truncate -s 1459978240 "$tmp/wrong.iso"
expect_refusal "disc --apply wrong SHA-1" 3 "ISO SHA-1 mismatch" \
  env CLOUDFLARE_ACCOUNT_ID=dummy R2_ACCESS_KEY_ID=dummy R2_SECRET_ACCESS_KEY=dummy \
  bash "$disc_upload" --apply --iso "$tmp/wrong.iso" --out "$tmp/chunks.json"
[ ! -e "$tmp/chunks.json" ] || fail "invalid disc wrote a chunk manifest"

if [ "$failures" -ne 0 ]; then
  echo "$failures guard(s) failed" >&2
  exit 1
fi
echo "all deploy and upload guards hold"
